CREATE DATABASE IF NOT EXISTS PAT_Turbinas;

CREATE TABLE IF NOT EXISTS experiemts (
    EXPERIMENTO_ID INTEGER SERIAL PRIMARY KEY,
    Torque [Nm] FLOAT NOT NULL,
    RPM INT NOT NULL,
    Frecuencia VARCHAR(255) NOT NULL,
    Caudal FLOAT NOT NULL,
    Presion_D FLOAT NOT NULL,
    Presion_G FLOAT NOT NULL,
    Power [kW] FLOAT NOT NULL, 
);
